MD = 200;

fi = fimplicit3(opt.p + opt.obj, [coord_lim, coord_lim/30, coord_lim], 'MeshDensity',MD, ...
       'EdgeColor', 'None','FaceColor', 'k', 'FaceAlpha', 0.3, ...
       'DisplayName', 'Safety Contour');